# Generated by Django 4.2.3 on 2023-08-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
